apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: gestion-proyectos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard   # Descomenta si usas minikube
  # storageClassName: gp2        # En AWS EKS usa esto
